### ISSUE TITLE
Match a specific attribute value doesn't work

### ISSUE THREAD

**Issue by Heart1010** [tcja/DOMDXMLParser#1]
More or less it works everything I've tested so far but not getting events with specific attribute values.
Example XML url: `http://nfs.faireconomy.media/ff_calendar_thisweek.xml`

Getting all events works
```php
$data = $xml->pickNode('event')->fetchData()->toArray();
```
But when I try to get only events from a specific date (tested with CDATA and without) I only get "bool(false)" as result
```php
$data = $xml->pickNode('date', '<![CDATA[05-10-2021]]>')->fetchData()->toArray();
$data = $xml->pickNode('date', '05-10-2021')->fetchData()->toArray();
```
or from a specific country
```php
$data = $xml->pickNode('country', 'AUD')->fetchData()->toArray();
```
So whenever I try to get specific attribute values this doesn't work.

**Comment by tcja** [comment]
Hi @Heart1010,

Thank you for your contribution and sorry for the delayed answer, I will look into this issue ASAP and keep you posted once it's fixed.

**Comment by tcja** [comment]
Finally had some time to review your issue, sorry for the delay.

Since your file uses the non-attribute layout-style, you don't need to specify the name of the attribute you are looking for, just set the specific data you want to retrieve, use this code for the first data set based on a date (please note that for CDATA just put what's inside of it without the `<![CDATA[specific-data-to-look-for]]>` tag, according to the file you provided on your link there is no such data matching the date you gave in example so the request will end up with a `bool` `false` response :

```php
$data = $xml->pickNode('05-10-2021')->fetchData()->toArray();
```

and for the seconde piece of code looking for data matching the country `AUD` : 

```php
$data = $xml->pickNode('AUD')->fetchData()->toArray();
```

That will show the data found as expected.

**Comment by Heart1010** [comment]
Thanks @tcja 👍
